Repository RushanCources/Project-38, pull requests merged in 2023-02, with the labels that each got.

#24 Issue19 registration creation
  portal/db.sqlite3
  portal/liceum38/settings.py
  portal/management/forms.py
  portal/management/migrations/0002_user_middle_name_user_role.py
  portal/management/migrations/0003_alter_user_role.py
  portal/management/models.py
  portal/management/urls.py
  portal/management/views.py
  portal/templates/home.html
  portal/templates/registration/register.html
Labels: enhancement, html, Django

#26 fixed migrations and 'manage.py'
  portal/db.sqlite3
  portal/manage.py
  portal/management/migrations/0001_initial.py
  portal/management/migrations/0002_user_middle_name_user_role.py
  portal/management/migrations/0003_alter_user_role.py
Labels: bug

#20 Issue13 models creation
  portal/.gitignore
  portal/db.sqlite3
  portal/liceum38/settings.py
  portal/management/models.py
  portal/management/urls.py
  portal/management/views.py
  portal/projects/models.py
  usefull_links.txt
Labels: Django
